spring: 
#  freemarker: 
#    suffix: .html
  redis:
    host: 59.110.172.165
    port: 6379
    password: null
    database: 2
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  datasource:
    url: jdbc:mysql://59.110.172.165:3306/blog2?characterEncoding=UTF8&useSSL=false
    username: root
    password: 321140726@gp
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8 #初始化连接大小
      min-idle: 5 #最小空闲连接数
      max-active: 10 #最大连接数
      query-timeout: 6000 #查询超时时间
      transaction-query-timeout: 6000 #事务查询超时时间
      remove-abandoned-timeout: 1800 #关闭空闲连接超时时间
      filter-class-names: stat
      filters: stat,config
#    platform: H2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
server:
  tomcat:
    uri-encoding: UTF-8
    

 