spring: 
#  freemarker: 
#    suffix: .html
  redis:
    host: 59.110.172.165
    port: 6379
    password: null
    database: 1
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  datasource:
    url: jdbc:mysql://59.110.172.165:3306/blog?characterEncoding=UTF8&useSSL=false
    username: root
    password: 321140726@gp
    driver-class-name: com.mysql.jdbc.Driver
#    platform: H2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
server:
  tomcat:
    uri-encoding: UTF-8
    

 